apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demospringboot-app
  name: demospringboot-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: demospringboot-app
  template:
    metadata:
      labels:
        app: demospringboot-app
    spec:
      containers:
        - name: my-demospringboot-app
          image: 533267220294.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
              name: http
              protocol: TCP
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demospringboot-app
    k8s-app: demospringboot-app
  name: demospringboot-app
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8085
  type: LoadBalancer
  selector:
    app: demospringboot-app
